export const USER_CURRENT_TASK_REQUEST = 'USER_CURRENT_TASK_REQUEST';
export const USER_CURRENT_TASK_SUCCESS = 'USER_CURRENT_TASK_SUCCESS';
export const USER_CURRENT_TASK_FAIL = 'USER_CURRENT_TASK_FAIL';

export const USER_GENERATE_NEW_TASK_REQUEST = 'USER_GENERATE_NEW_TASK_REQUEST';
export const USER_GENERATE_NEW_TASK_SUCCESS = 'USER_GENERATE_NEW_TASK_SUCCESS';
export const USER_GENERATE_NEW_TASK_FAIL = 'USER_GENERATE_NEW_TASK_FAIL';
